---
title: "Ofav BW environmental Co-factors and SCTLD"
author: "Ana Palacio-Castro"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 6
    df_print: paged
    toc: yes
    toc_float: true
#bibliography: packages.bib
#nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE) 
                      #fig.width=4, fig.height=3 )
```

# General project set-up 

```{r libraries, results="hide"}

# Libraries
  library(reshape2)
  library(tidyverse)

# Graphs
# Plots
MyTheme<-theme_bw() +  
theme(legend.position="top",
          plot.background=element_blank(),
          #axis.text.x = element_text(angle = 90, vjust = 0.5),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          legend.title = element_blank(),
          panel.background =element_rect(fill = NA, 
                                         color = "black"))#+
  #guides(fill=guide_legend(nrow=2,byrow=TRUE), shape=guide_legend(nrow=3,byrow=TRUE))

Treat_fill<-scale_fill_manual(values =
                           c("#2b83ba", "#003399",
                             "#d7191c", "#660000"))

Treat_colour<-scale_colour_manual(values =
                           c("#2b83ba", "#003399",
                             "#d7191c", "#660000"))
    
# Data    
  # Fragment list
  CurrentFragments<-read.csv("Metadata/Fragment_Replicate.csv", header = T)
```

# Raw data

Data files
```{r}

# # BW data
#   Raw_Data<-read.csv("RawData.csv")
#   n_RunA <- data.frame(table(Raw_Data$Fragment))
#   colnames(n_RunA)<-c("Fragment","Samples")
#   
#   N_Sample_Date<-Raw_Data %>%
#          group_by(Fragment, Date) %>%
#          dplyr::summarise(N = n())
#   N_Sample_Date

```

Re organize the data

```{r}
# Raw_Data_Wide<-reshape(Raw_Data, idvar="Fragment", timevar = "Time", direction = "wide")
# 
# Raw_Data_Wide<-dplyr::left_join(Raw_Data_Wide,CurrentFragments, by ="Fragment")
# #Raw_Data_2<-dplyr::left_join(Raw_Data,CurrentFragments, by ="Fragment")
# #Typos<-dplyr::anti_join(Raw_Data, CurrentFragments, by ="Fragment")
# 
# Raw_Data_Wide<-dplyr::left_join(Raw_Data_Wide, n_RunA, by="Fragment")
# Raw_Data_Wide<-left_join(Raw_Data_Wide, Location, by=c("Colony"))
# 
# write.csv(Raw_Data_Wide, "Raw_Data_Wide_bleching.csv",
#           row.names = FALSE)
# 
# # Clean working space
# rm(list = ls())
```

# Organized data

After data manupulation

```{r}

# Long (processed) data
Corrected_long<-read.csv("Long_data_Growth.csv")
  n_RunB <- data.frame(table(Corrected_long$Fragment))
  colnames(n_RunB)<-c("Fragment","Samples")

Corrected_long<-dplyr::left_join(Corrected_long, CurrentFragments, by ="Fragment")

Corrected_long$N_T<-factor(paste(Corrected_long$Nutrients, Corrected_long$Temp, sep = "_"))
Corrected_long<-Corrected_long %>% drop_na(Temp, Nutrients)
Corrected_long$N_T<-factor(Corrected_long$N_T, levels = c("LN_28", "HN_28", "LN_31", "HN_31"))

summary(Corrected_long)
#Typos<-dplyr::anti_join(Corrected_long, CurrentFragments, by ="Fragment")
# Corrected_long<-dplyr::left_join(Corrected_long, n_RunB, by ="Fragment")
# 
# 
#     Corrected_long$Date_I<-as.Date(Corrected_long$Date_I, "%m/%d/%y")
#     Corrected_long$Date_F<-as.Date(Corrected_long$Date_F, "%m/%d/%y")
#     # Corrected_long$Date_I<-as.Date(Corrected_long$Date_I, "%Y-%m-%d")
#     # Corrected_long$Date_F<-as.Date(Corrected_long$Date_F, "%Y-%m-%d")
#     Corrected_long$Days<-(as.numeric(as.Date(Corrected_long$Date_F))-18173)
#     Corrected_long$Day<-(as.factor(Corrected_long$Days))
#     Corrected_long$Colony <- paste("P",Corrected_long$Colony, sep = "_" )
#     Corrected_long$Colony <- as.factor(Corrected_long$Colony)
#     
#     Corrected_long$SampleID <- paste(Corrected_long$Colony, Corrected_long$Date_F, sep = "_")
# 
# # Remove dead frags
#   Dying_frags<-filter(Corrected_long, Notes_I=="Almost Dead")
#   Dying_frags<-select(Dying_frags, Fragment)
#   Corrected_long<-anti_join(Corrected_long, Dying_frags, by = "Fragment")
#   str(Corrected_long)

#write.csv(Corrected_long, "Corrected_long3.csv", row.names = FALSE)

  
```

## Relative growth

```{r}
head(Corrected_long)
BW<- ggplot(Corrected_long, aes (Genotype, Growth..mg.g.d., colour=factor(N_T))) + 
  MyTheme + Treat_fill+Treat_colour+
       stat_summary(fun.data = "mean_cl_boot",geom = "errorbar",
               width = 0.2, position=position_dodge(width=0.2))+
        stat_summary(fun.y=mean, geom="point", 
                position=position_dodge(width=0.2), size =2, alpha=1) +
        stat_summary(fun.y=mean, geom="line",  position=position_dodge(width=0.2)) + 
        #geom_point()+
      
      #scale_x_continuous(name="Days", 
       #                  breaks = seq(0, 30, by=15)) +
      scale_y_continuous(name="Growth (mg / g d)", 
                       breaks = seq(-1, 2, by=0.5)) +
    
    theme(legend.position="top",
        legend.title = element_blank(), 
        strip.background =element_rect(fill=NA)) 
BW

```
